#Problem: Code a number guesing game for a user . The number is being generated by the computer. Guide the user about the number being high or low till the user guesses it. Handle the errors when the user enters an invalid input

import random as r
comp = r.randint(1,101)

while True: 
    try: #This is used to handle errors in python
        user= int(input("Enter a number from 1 to 100: "))
    except ValueError: #Any value error that occurs, will run this block of code below
        print("Please enter a valid number. ")
    if user > comp:
        print("Guessed number is too high. ")
    elif user < comp:
        print("Guessed number is too low. ")
    elif user == comp:
        print("Congratulations, you have guessed the number")
    else: 
        print("invalid input")